[alias]
xtask = "run --package xtask --"

[env]
ROOT_DIR = { value = ".", relative = true }
PROFILE = "debug"  # build debug by default

#[build]
#rustflags = ["-C", "llvm-args=-align-all-functions=8"]
