[package]
name = "zynx-bridge-common"
version.workspace = true
edition.workspace = true

[dependencies]
jni-sys = { workspace = true }
nix = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }