name: Build

on:
  workflow_dispatch:
  push:
    branches: [master, workflow]
  pull_request:
    branches: [master, workflow]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Rust
        run: |
          rustup update stable
          rustup target add aarch64-linux-android
          rustup toolchain install nightly --component rust-src

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - name: Build
        run: just build-release
