name: Build

on:
  workflow_dispatch:
  push:
    branches: [master, workflow]
  pull_request:
    branches: [master, workflow]

env:
  CARGO_TERM_COLOR: always
  ONDK_VERSION: "r29.5"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        profile: [debug, release]
        zygisk: [zygisk, no-zygisk]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Setup Protoc
        uses: arduino/setup-protoc@v3

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Rust (nightly for eBPF)
        run: rustup toolchain install nightly --component rust-src

      - name: Setup ONDK
        run: python3 scripts/setup-ondk.py --version $ONDK_VERSION

      - name: Install bpf-linker
        run: cargo install bpf-linker

      - name: Build
        run: just build-${{ matrix.profile }} ${{ matrix.zygisk }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: zynx-${{ matrix.profile }}-${{ matrix.zygisk }}
          path: |
            target/aarch64-linux-android/${{ matrix.profile }}/zynx
            target/aarch64-linux-android/${{ matrix.profile }}/zynx.dwp
