[package]
name = "zynx-bridge-types"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
jni-sys = { workspace = true }
nix = { workspace = true }
rkyv = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
